# -*- coding: utf-8 -*-
"""hangman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hstxQwWe1j-dkTEam0myIfwqYd-g9lY4
"""

import random

def get_word():
    # This function returns a random word from a list of words
    words = ["python", "computer", "programming", "algorithm", "variable", "function", "string", "integer"]
    return random.choice(words)

def play_game():
    word = get_word()
    word_letters = set(word)  # set of letters in the word
    alphabet = set('abcdefghijklmnopqrstuvwxyz')
    used_letters = set()  # set of letters already guessed by the player
    lives = 7  # number of lives

    # loop until the player has no lives left or has guessed the word
    while len(word_letters) > 0 and lives > 0:
        # print the used letters and the remaining lives
        print("You have", lives, "lives left and you have used these letters: ", ' '.join(used_letters))

        # create a list of the letters in the word that haven't been guessed yet
        word_list = [letter if letter in used_letters else '-' for letter in word]

        # print the current state of the word
        print("Current word: ", ' '.join(word_list))

        # get a guess from the player and make sure it's a valid letter
        guess = input("Guess a letter: ").lower()
        if guess in alphabet - used_letters:
            used_letters.add(guess)
            if guess in word_letters:
                word_letters.remove(guess)
            else:
                lives = lives - 1
                print("Letter is not in the word.")
        elif guess in used_letters:
            print("You have already guessed that letter. Please try again.")
        else:
            print("Invalid character. Please try again.")

    # the game is over, print the result
    if lives == 0:
        print("You died, sorry. The word was", word)
    else:
        print("Congratulations! You guessed the word", word, "in", len(used_letters), "tries.")

# start the game
play_game()